name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses actions/checkout@v2
      - name: Login to ghcr.Io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build . -t ghcr.io/309theddge/registry-test:latest
          docker run ghcr.io/309theddge/registry-test:latest
          docker push ghcr.io/309theddge/registry-test:latest
